name: 🦟🏸 Bugfix
description: Relate um bug ou erro
title: "[MÓDULO]: [RECURSO]: [Descrição simples sobre o bug] "
labels: ["bug"]
body:
  - type: dropdown
    attributes:
      label: Tipo de Bug
      options:
        - "back-end"
        - "front-end"
        - "infra"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Descrição
      description: "Descreva o bug que você irá corrigir."
    validations:
      required: true