name: ✨ Feature
description: Sugira uma nova funcionalidade
title: "[MÓDULO]: [RECURSO]: [Descrição simples sobre a feature] "
labels: ["feature"]
body:
  - type: dropdown
    attributes:
      label: Time responsável
      description: "Selecione o time responsável pela feature."
      options:
        - "back-end"
        - "front-end"
        - "infra"
        - "todos"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Descrição
      description: "Descreva a feature que você irá implementar."
      value: |
        **Recurso que será desenvolvido**:  
        (ex.: "Implementar o recurso de login com Google")  

        **ID dos requisitos funcionais relacionados**:  
        [RF05]  

        **Objetivos intermediários**:  
        1. ...  
        2. ...  

        **Informações Adicionais**:  
        (referências, etc.)
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: "Controle de Versão"
      options:
        - label: "Está implementando um novo recurso?"
          required: false