name: Create PRs from main to develop and hotfix

on:
  push:
    branches:
      - main

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Create PR to develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh pr list --base develop --head main --json number --jq '.[0]' > /dev/null; then
            gh pr create \
              --title "Merge main into develop" \
              --body "Automatic PR to keep develop up to date with main" \
              --base develop \
              --head main
          else
            echo "PR from main to develop already exists"
          fi


      - name: Create PR to hotfix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ! gh pr list --base hotfix --head main --json number --jq '.[0]' > /dev/null; then
            gh pr create \
              --title "Merge main into hotfix" \
              --body "Automatic PR to keep hotfix up to date with main" \
              --base hotfix \
              --head main
          else
            echo "PR from main to hotfix already exists"
          fi

