name: Create PR from main to develop and hotfix

on:
  push:
    branches:
      - main

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create PR to develop
        uses: devops-infra/action-pull-request@v0.5.2
        with:
          source_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Merge main into develop'
          body: 'Automatic PR: Sync main with develop'

      - name: Create PR to hotfix
        uses: devops-infra/action-pull-request@v0.5.2
        with:
          source_branch: main
          target_branch: hotfix
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Merge main into hotfix'
          body: 'Automatic PR: Sync main with hotfix'
