name: Auto-Sync Main to Protected Branches

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * 1-5' # Dias úteis às 9h (ajuste conforme fuso horário)

jobs:
  create-sync-prs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        target-branch: ['develop', 'hotfix']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Sync PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: sync main to ${{ matrix.target-branch }}"
          title: "🔀 Sync: main → ${{ matrix.target-branch }}"
          body: "Automated sync from main branch"
          branch: "sync/main-to-${{ matrix.target-branch }}"
          base: "${{ matrix.target-branch }}"
          labels: "automated"
          delete-branch: true
          # Configurações de auto-merge CORRETAS:
          auto-merge: true
          auto-merge-method: merge