name: Create PRs from main to develop and hotfix

on:
  push:
    branches:
      - main

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Create PR from main to develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list --base develop --head main --json number --jq '.[0]' | grep -q null; then
            gh pr create \
              --base develop \
              --head main \
              --title "Merge main into develop" \
              --body "Automated PR to keep develop up to date with main"
          else
            echo "PR from main to develop already exists"
          fi

      - name: Create PR from main to hotfix
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if gh pr list --base hotfix --head main --json number --jq '.[0]' | grep -q null; then
            gh pr create \
              --base hotfix \
              --head main \
              --title "Merge main into hotfix" \
              --body "Automated PR to keep hotfix up to date with main"
          else
            echo "PR from main to hotfix already exists"
          fi
