name: Create PRs from main to develop and hotfix

on:
  push:
    branches:
      - main

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Setup GitHub CLI
        uses: cli/cli-action@v2

      - name: Create PR from main to develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if PR from main to develop exists..."
          if gh pr list --base develop --head main --json number --jq '.[0]' | grep -q null; then
            echo "Creating PR from main to develop..."
            gh pr create \
              --base develop \
              --head main \
              --title "Merge main into develop" \
              --body "Automated PR to keep develop up to date with main"
          else
            echo "PR from main to develop already exists"
          fi

      - name: Create PR from main to hotfix
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking if PR from main to hotfix exists..."
          if gh pr list --base hotfix --head main --json number --jq '.[0]' | grep -q null; then
            echo "Creating PR from main to hotfix..."
            gh pr create \
              --base hotfix \
              --head main \
              --title "Merge main into hotfix" \
              --body "Automated PR to keep hotfix up to date with main"
          else
            echo "PR from main to hotfix already exists"
          fi
